apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fgastores.openfga.sathiyaraman-m.com
spec:
  group: openfga.sathiyaraman-m.com
  names:
    kind: FgaStore
    listKind: FgaStoreList
    plural: fgastores
    singular: fgastore
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              connectionConfigRef:
                description: Name of the Connection Config to use to connect an OpenFGA instance
                type: string
            required:
            - connectionConfigRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      nullable: true
                      type: integer
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
              storeId:
                description: Store ID for the OpenFGA Store
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}