apiVersion: openfga.sathiyaraman-m.com/v1
kind: FgaAuthorizationModel
metadata:
  name: demo-model
spec:
  storeRef: demo-store
  modelDsl: |
    model
      schema 1.1

    type user

    type group
      relations
      define member: [user]

    type document
      relations
      define viewer: [user, group#member]
